---
title: "visualitations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries for plotting, echo = FALSE, warning=FALSE}
library(ggplot2)
library(gganimate)
library(gridExtra)
source("C:/Users/Usuario/Desktop/dykstra/ProgramasGuillermo/Projections.R")

dir.create("C:/Rtmp")
cat("TMPDIR = C:\\\\Rtmp", file = "~/.Renviron", sep = "\n")

```

```{r plots, echo = FALSE, warning=FALSE}
###################### Plot for lineal example ####################
a1p = c(0.01,1)
a2p = c(2,1)
Ap = rbind(a1p, a2p)
bp = c(0.5,-1)
x0 = c(2,1)
x0 = c(0,1.5)
W = rbind(c(1,0),c(0,1))
M = length(as.vector(bp)) 
N = length(x0)
e0 = matrix(rep(0,N*M),nrow = M, ncol = N)
DFl = data.frame("x_1" = x0[1],"x_2" = x0[2])
for (n in 1:10) {
  i = 1+(n-1)%%M
  x0e0 = as.numeric(x0) + e0[i,] 
  x = P_Half_space(x0e0,as.matrix(Ap)[i,],as.vector(bp)[i],W)
  e = as.numeric(x0) + e0[i,] - x 
  e0[i,] = e
  x0 = x
  DFl = rbind(DFl,x0e0)
  DFl = rbind(DFl,x)
  #print(x)
}
DFl = cbind(DFl,"id" = 1:length(DFl[,1]))
# data frame lineal constraints
DFlc = data.frame( x= c(-1, -1,-0.75,-0.25), y = c(-0.5,0.5,0.5,-0.5))

colors = c('black','black',ifelse(1:(length(DFl[,1])-2)%%2 == 0, 'black','red'))
           
pl = ggplot(data = DFl, aes(x = x_1, y = x_2)) +
  geom_abline(aes(intercept = bp[1]/a1p[2],slope = -a1p[1]/a1p[2]),
              size =1.1,color = "blue") +
  geom_abline(aes( intercept = bp[2]/a2p[2], slope = -a2p[1]/a2p[2]),
              size =1.1, color = "blue") +
  geom_polygon(data = DFlc, mapping = aes(x = x, y = y), alpha=0.3) +
  geom_point() + 
  geom_path(col=colors) +
  coord_fixed()

##################### Plot for lineal ball(r=1) example ########################
x0 = c(1.5,2)
asb = c(0,1)
bsb = -3/4
e0 = matrix(rep(0,2*2),nrow = 2, ncol = 2)
DFlb = data.frame("x_1" = x0[1],"x_2" = x0[2])
# Dykstra algorithm
for (n in 1:6) {
  i = 1 #circulo
  x0e0 = as.numeric(x0) + e0[i,]
  x = P_ball(x0e0)
  e = as.numeric(x0) + e0[i,] - x 
  e0[i,] = e
  x0 = x
  DFlb = rbind(DFlb,x0e0)
  DFlb = rbind(DFlb,x)
  i = 2 #semiespacio
  x0e0 = as.numeric(x0) + e0[i,]
  x = P_Half_space(x0e0,asb,bsb,W=diag(length(x0)))
  e = as.numeric(x0) + e0[i,] - x 
  e0[i,] = e
  x0 = x
  DFlb = rbind(DFlb,x0e0)
  DFlb = rbind(DFlb,x)
}
# DF with the x of teh sucesive projections
DFlb = cbind(DFlb,"id" = 1:nrow(DFlb))
#colors of the sucesive projections
colorsb = c('black','black',ifelse(1:(length(DFlb[,1])-2)%%2 == 0, 'black','red'))
# DF with lineal-ball constraints limits for geom_polygon (r = 1, h = -3/4)
xlbc = seq(-sqrt(1-(3/4)^2),sqrt(1-(3/4)^2),0.001)
ylbc = -sqrt(1^2 - xlbc^2) 
DFlbc = data.frame(x = xlbc, y = ylbc) 
# Plots  
plb = ggplot(data = DFlb, aes(x = x_1, y = x_2)) +
  geom_point() +
  geom_abline(aes(intercept = bsb/asb[2],slope = -asb[1]/asb[2]),
              size =1,color = "blue") +
  ggforce::geom_circle(inherit.aes = FALSE, aes(x0 = 0, y0 = 0, r = 1), 
                       size = 1,  color = "blue") +
  coord_fixed() +
  geom_path(col=colorsb) +
  geom_polygon(inherit.aes = FALSE, data = DFlbc, mapping = aes(x = x, y = y), alpha=0.3)


########################## 2 ball example #########################
x0 =c(0,2.5)
r = c(2,1)
centers = matrix(c(2,0,0,0),nrow = 2, ncol = 2,byrow = TRUE)
M = length(r) ## nº de bolas(subconjuntos convexos = restricciones)
N = length(x0) ## dimension del vecotr a proyectar = nº de variables
E = matrix(rep(0,N*M),nrow = M, ncol = N)

DFb = data.frame(x_1 = x0[1], x_2 = x0[2])
for (n in 1:6) {
  i = 1+(n-1)%%M
  x0e = as.numeric(x0) + E[i,]
  x0e_prima = (x0e - centers[i,])/r[i]# reescalamos 
  x = P_ball(x0e_prima,W) # proyectamos sobre la "nueva" bola unidad (en el nuevo sist.)
  x = x * r[i] + centers[i,]# recuperamos el sistema de coordenadas anterior
  e = as.numeric(x0) + E[i,] - x
  E[i,] = e
  x0 = x
  DFb = rbind(DFb, x0e)
  DFb = rbind(DFb, x)
}
DFb = cbind(DFb,"id" = 1:nrow(DFb))

colorb = c('black','black',ifelse(1:(length(DFb[,1])-2)%%2 == 0, 'black','red'))

pb = ggplot(data = DFb, aes(x = x_1, y = x_2)) + 
  geom_point() +
  ggforce::geom_circle(inherit.aes = FALSE, aes(x0 = 0, y0 = 0, r = 1), color = "blue") +
  ggforce::geom_circle(inherit.aes = FALSE, aes(x0 = 2, y0 = 0, r = 2), color = "blue") +
  geom_path(col = colorb) +
  coord_fixed()

grid.arrange(arrangeGrob(pl, plb, pb, ncol = 3), widths = 10)
```

```{r gifs, echo = FALSE, warning=FALSE, eval=TRUE}
al = ggplot(data = DFl, aes(x = x_1, y = x_2)) +
  geom_abline(aes(intercept = bp[1]/a1p[2],slope = -a1p[1]/a1p[2]),
                size =1.1,color = "blue") +
  geom_abline(aes( intercept = bp[2]/a2p[2], slope = -a2p[1]/a2p[2]),
                size =1.1, color = "blue") +
  #geom_polygon(aes(x = x, y = y)) +
  geom_point() + 
  geom_path(col=colors) +
  transition_reveal(id) +
  geom_polygon(data = DFlc, mapping = aes(x = x, y = y), alpha=0.3) +
  #expand_limits(x = c(-2, 0.5), y = 0)
  xlim(-1,0.25) +
  ylim(-0.5,1.5)
  
animate(al, nframes = 50)
```